# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog

from frontend import WelcomeScreen as ws

class Ui_SVA(object):
    def setupUi(self, SVA):
        SVA.setObjectName("SVA")
        SVA.setEnabled(True)
        SVA.resize(569, 330)
        font = QtGui.QFont()
        font.setKerning(True)
        SVA.setFont(font)
        self.label = QtWidgets.QLabel(SVA)
        self.label.setGeometry(QtCore.QRect(230, 30, 101, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(SVA)
        self.label_2.setGeometry(QtCore.QRect(100, 100, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(SVA)
        self.lineEdit.setGeometry(QtCore.QRect(120, 130, 331, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(SVA)
        self.label_3.setGeometry(QtCore.QRect(100, 170, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(SVA)
        self.lineEdit_2.setGeometry(QtCore.QRect(120, 200, 331, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(SVA)
        self.pushButton.setGeometry(QtCore.QRect(210, 270, 111, 31))
        self.pushButton.setObjectName("pushButton")


        self.retranslateUi(SVA)
        QtCore.QMetaObject.connectSlotsByName(SVA)

    def retranslateUi(self, SVA):
        _translate = QtCore.QCoreApplication.translate
        SVA.setWindowTitle(_translate("SVA", "School Verification System"))
        self.label.setText(_translate("SVA", "Login"))
        self.label_2.setText(_translate("SVA", "Username"))
        self.label_3.setText(_translate("SVA", "Password"))
        self.pushButton.setText(_translate("SVA", "Login"))
