# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'verificationScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Verification(object):
    def setupUi(self, Verification):
        Verification.setObjectName("Verification")
        Verification.resize(619, 375)
        self.imageViewer = QtWidgets.QGraphicsView(Verification)
        self.imageViewer.setGeometry(QtCore.QRect(20, 10, 151, 151))
        self.imageViewer.setObjectName("imageViewer")
        self.statusLabel = QtWidgets.QLabel(Verification)
        self.statusLabel.setGeometry(QtCore.QRect(400, 20, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.statusLabel.setFont(font)
        self.statusLabel.setObjectName("statusLabel")
        self.statusMessage = QtWidgets.QLabel(Verification)
        self.statusMessage.setGeometry(QtCore.QRect(400, 90, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.statusMessage.setFont(font)
        self.statusMessage.setObjectName("statusMessage")
        self.lightStatus = QtWidgets.QGraphicsView(Verification)
        self.lightStatus.setGeometry(QtCore.QRect(510, 10, 61, 51))
        self.lightStatus.setFrameShape(QtWidgets.QFrame.VLine)
        self.lightStatus.setObjectName("lightStatus")
        self.releaseButton = QtWidgets.QPushButton(Verification)
        self.releaseButton.setGeometry(QtCore.QRect(390, 230, 191, 41))
        self.releaseButton.setObjectName("releaseButton")

        self.nextButton = QtWidgets.QPushButton(Verification)
        self.nextButton.setGeometry(QtCore.QRect(320, 200, 191, 41))
        self.nextButton.setObjectName("nextButton")

        self.cancelButton = QtWidgets.QPushButton(Verification)
        self.cancelButton.setGeometry(QtCore.QRect(390, 310, 191, 41))
        self.cancelButton.setObjectName("cancelButton")
        self.qrCode = QtWidgets.QGraphicsView(Verification)
        self.qrCode.setGeometry(QtCore.QRect(230, 30, 101, 101))
        self.qrCode.setObjectName("qrCode")
        self.nameLabel = QtWidgets.QLabel(Verification)
        self.nameLabel.setGeometry(QtCore.QRect(30, 190, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nameLabel.setFont(font)
        self.nameLabel.setObjectName("nameLabel")
        self.classLabel = QtWidgets.QLabel(Verification)
        self.classLabel.setGeometry(QtCore.QRect(30, 250, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.classLabel.setFont(font)
        self.classLabel.setObjectName("classLabel")
        self.pickerLabel = QtWidgets.QLabel(Verification)
        self.pickerLabel.setGeometry(QtCore.QRect(30, 320, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pickerLabel.setFont(font)
        self.pickerLabel.setObjectName("pickerLabel")
        self.nameMessage = QtWidgets.QLabel(Verification)
        self.nameMessage.setGeometry(QtCore.QRect(90, 180, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.nameMessage.setFont(font)
        self.nameMessage.setText("")
        self.nameMessage.setObjectName("nameMessage")
        self.classMessage = QtWidgets.QLabel(Verification)
        self.classMessage.setGeometry(QtCore.QRect(90, 250, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.classMessage.setFont(font)
        self.classMessage.setText("")
        self.classMessage.setObjectName("classMessage")
        self.pickerMessage = QtWidgets.QLabel(Verification)
        self.pickerMessage.setGeometry(QtCore.QRect(90, 320, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pickerMessage.setFont(font)
        self.pickerMessage.setText("")
        self.pickerMessage.setObjectName("pickerMessage")

        self.retranslateUi(Verification)
        QtCore.QMetaObject.connectSlotsByName(Verification)

    def retranslateUi(self, Verification):
        _translate = QtCore.QCoreApplication.translate
        Verification.setWindowTitle(_translate("Verification", "Dialog"))
        self.statusLabel.setText(_translate("Verification", "Status: "))
        self.statusMessage.setText(_translate("Verification", "Not Ready to be Released"))
        self.releaseButton.setText(_translate("Verification", "Release"))
        self.cancelButton.setText(_translate("Verification", "Cancel"))
        self.nameLabel.setText(_translate("Verification", "Name: "))
        self.classLabel.setText(_translate("Verification", "Class:"))
        self.pickerLabel.setText(_translate("Verification", "Picker:"))
