# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WelcomeScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WelcomeScreen(object):
    def setupUi(self, WelcomeScreen):
        WelcomeScreen.setObjectName("WelcomeScreen")
        WelcomeScreen.resize(524, 245)
        self.label = QtWidgets.QLabel(WelcomeScreen)
        self.label.setGeometry(QtCore.QRect(80, 0, 371, 91))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(WelcomeScreen)
        self.pushButton.setGeometry(QtCore.QRect(50, 100, 161, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(WelcomeScreen)
        self.pushButton_2.setGeometry(QtCore.QRect(310, 100, 161, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(WelcomeScreen)
        QtCore.QMetaObject.connectSlotsByName(WelcomeScreen)

    def retranslateUi(self, WelcomeScreen):
        _translate = QtCore.QCoreApplication.translate
        WelcomeScreen.setWindowTitle(_translate("WelcomeScreen", "Dialog"))
        self.label.setText(_translate("WelcomeScreen", "Welcome To Student Verification System"))
        self.pushButton.setText(_translate("WelcomeScreen", "Add Student Information"))
        self.pushButton_2.setText(_translate("WelcomeScreen", "Add Parent Information"))
