# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WelcomeMain.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WelcomeSSA(object):
    def setupUi(self, WelcomeSSA):
        WelcomeSSA.setObjectName("WelcomeSSA")
        WelcomeSSA.resize(506, 370)
        self.label = QtWidgets.QLabel(WelcomeSSA)
        self.label.setGeometry(QtCore.QRect(20, 10, 501, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.releaseButton = QtWidgets.QPushButton(WelcomeSSA)
        self.releaseButton.setGeometry(QtCore.QRect(100, 110, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.releaseButton.setFont(font)
        self.releaseButton.setObjectName("releaseButton")
        self.pushButton_2 = QtWidgets.QPushButton(WelcomeSSA)
        self.pushButton_2.setGeometry(QtCore.QRect(100, 200, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(WelcomeSSA)
        self.pushButton_3.setGeometry(QtCore.QRect(100, 290, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(WelcomeSSA)
        QtCore.QMetaObject.connectSlotsByName(WelcomeSSA)

    def retranslateUi(self, WelcomeSSA):
        _translate = QtCore.QCoreApplication.translate
        WelcomeSSA.setWindowTitle(_translate("WelcomeSSA", "Dialog"))
        self.label.setText(_translate("WelcomeSSA", "Welcome to School Security Application"))
        self.releaseButton.setText(_translate("WelcomeSSA", "Start Student Release"))
        self.pushButton_2.setText(_translate("WelcomeSSA", "Register Student"))
        self.pushButton_3.setText(_translate("WelcomeSSA", "Edit Parent/Picker Credentials"))
